"""phase 2: skills, questions, answers, evaluations, reports, llm_calls

Revision ID: b5fd9b71b623
Revises: 775d54289729
Create Date: 2026-07-27 02:20:45.031319
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5fd9b71b623'
down_revision: str | None = '775d54289729'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_skills',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_skills_resume_id'), 'extracted_skills', ['resume_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_session_id'), 'llm_calls', ['session_id'], unique=False)
    op.create_table('questions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('expected_concepts', sa.JSON(), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_question_session_ordinal')
    )
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    op.create_table('reports',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('per_topic', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('pdf_uri', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=True)
    op.create_table('answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=True),
    sa.Column('paste_events', sa.Integer(), nullable=False),
    sa.Column('keystroke_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'idempotency_key', name='uq_answer_question_idem')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('concept_coverage', sa.JSON(), nullable=False),
    sa.Column('llm_scores', sa.JSON(), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_answer_id'), 'evaluations', ['answer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_answer_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_llm_calls_session_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_extracted_skills_resume_id'), table_name='extracted_skills')
    op.drop_table('extracted_skills')
    # ### end Alembic commands ###
